<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    public function run()
    {
        DB::table('ingredients')->insert([
            // ============ GOMBALEVES ============
            [
                'ingredientName' => 'Friss gomba',
                'ingredientType' => 'Zöldség',
                'energy' => 22,
                'protein' => 3,
                'carbohydrate' => 3,
                'fat' => 0,
                'sodium' => 5,
                'sugar' => 2,
                'fiber' => 1,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Hagyma',
                'ingredientType' => 'Zöldség',
                'energy' => 40,
                'protein' => 1,
                'carbohydrate' => 9,
                'fat' => 0,
                'sodium' => 4,
                'sugar' => 4,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Tejföl',
                'ingredientType' => 'Tejtermék',
                'energy' => 135,
                'protein' => 3,
                'carbohydrate' => 4,
                'fat' => 12,
                'sodium' => 40,
                'sugar' => 4,
                'fiber' => 0,
                'isAvailable' => true
            ],
            
            // ============ MARHAPÖRKÖLT ============
            [
                'ingredientName' => 'Marhahús (comb)',
                'ingredientType' => 'Hús',
                'energy' => 250,
                'protein' => 26,
                'carbohydrate' => 0,
                'fat' => 15,
                'sodium' => 70,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Vöröshagyma',
                'ingredientType' => 'Zöldség',
                'energy' => 40,
                'protein' => 1,
                'carbohydrate' => 9,
                'fat' => 0,
                'sodium' => 4,
                'sugar' => 4,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Piros paprika',
                'ingredientType' => 'Zöldség',
                'energy' => 31,
                'protein' => 1,
                'carbohydrate' => 6,
                'fat' => 0,
                'sodium' => 4,
                'sugar' => 4,
                'fiber' => 2,
                'isAvailable' => true
            ],
            
            // ============ SAJTOS TÉSZT ============
            [
                'ingredientName' => 'Tészta (spaghetti)',
                'ingredientType' => 'Egyéb',
                'energy' => 131,
                'protein' => 5,
                'carbohydrate' => 25,
                'fat' => 1,
                'sodium' => 1,
                'sugar' => 1,
                'fiber' => 1,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Trappista sajt',
                'ingredientType' => 'Tejtermék',
                'energy' => 350,
                'protein' => 25,
                'carbohydrate' => 2,
                'fat' => 28,
                'sodium' => 620,
                'sugar' => 1,
                'fiber' => 0,
                'isAvailable' => true
            ],
                        [
                'ingredientName' => 'Tej',
                'ingredientType' => 'Tejtermék',
                'energy' => 350,
                'protein' => 25,
                'carbohydrate' => 2,
                'fat' => 28,
                'sodium' => 620,
                'sugar' => 1,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Tejszín',
                'ingredientType' => 'Tejtermék',
                'energy' => 345,
                'protein' => 2,
                'carbohydrate' => 3,
                'fat' => 36,
                'sodium' => 40,
                'sugar' => 3,
                'fiber' => 0,
                'isAvailable' => true
            ],
            
            // ============ LASAGNE ============
            [
                'ingredientName' => 'Lasagne lap',
                'ingredientType' => 'Egyéb',
                'energy' => 370,
                'protein' => 12,
                'carbohydrate' => 74,
                'fat' => 2,
                'sodium' => 10,
                'sugar' => 3,
                'fiber' => 3,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Darált marhahús',
                'ingredientType' => 'Hús',
                'energy' => 250,
                'protein' => 26,
                'carbohydrate' => 0,
                'fat' => 16,
                'sodium' => 75,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Paradicsom szósz',
                'ingredientType' => 'Egyéb',
                'energy' => 80,
                'protein' => 2,
                'carbohydrate' => 12,
                'fat' => 3,
                'sodium' => 400,
                'sugar' => 9,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Mozzarella sajt',
                'ingredientType' => 'Tejtermék',
                'energy' => 280,
                'protein' => 22,
                'carbohydrate' => 2,
                'fat' => 22,
                'sodium' => 400,
                'sugar' => 1,
                'fiber' => 0,
                'isAvailable' => true
            ],
            
            // ============ HÚSLEVES ============
            [
                'ingredientName' => 'Csirkemell',
                'ingredientType' => 'Hús',
                'energy' => 165,
                'protein' => 31,
                'carbohydrate' => 0,
                'fat' => 3,
                'sodium' => 74,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Répa',
                'ingredientType' => 'Zöldség',
                'energy' => 41,
                'protein' => 1,
                'carbohydrate' => 10,
                'fat' => 0,
                'sodium' => 69,
                'sugar' => 5,
                'fiber' => 3,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Petrezselyem gyökér',
                'ingredientType' => 'Zöldség',
                'energy' => 55,
                'protein' => 2,
                'carbohydrate' => 12,
                'fat' => 0,
                'sodium' => 60,
                'sugar' => 2,
                'fiber' => 4,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Zeller',
                'ingredientType' => 'Zöldség',
                'energy' => 42,
                'protein' => 2,
                'carbohydrate' => 9,
                'fat' => 0,
                'sodium' => 80,
                'sugar' => 2,
                'fiber' => 2,
                'isAvailable' => true
            ],
            
            // ============ GRILLCSIRKE ============
            [
                'ingredientName' => 'Csirkecomb',
                'ingredientType' => 'Hús',
                'energy' => 240,
                'protein' => 27,
                'carbohydrate' => 0,
                'fat' => 14,
                'sodium' => 90,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Olívaolaj',
                'ingredientType' => 'Egyéb',
                'energy' => 884,
                'protein' => 0,
                'carbohydrate' => 0,
                'fat' => 100,
                'sodium' => 0,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Fokhagyma',
                'ingredientType' => 'Zöldség',
                'energy' => 149,
                'protein' => 6,
                'carbohydrate' => 33,
                'fat' => 0,
                'sodium' => 17,
                'sugar' => 1,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Citromlé',
                'ingredientType' => 'Egyéb',
                'energy' => 29,
                'protein' => 1,
                'carbohydrate' => 9,
                'fat' => 0,
                'sodium' => 1,
                'sugar' => 2,
                'fiber' => 0,
                'isAvailable' => true
            ],
            
            // ============ GYÜMÖLCSALÁTA ============
            [
                'ingredientName' => 'Alma',
                'ingredientType' => 'Gyümölcs',
                'energy' => 52,
                'protein' => 0,
                'carbohydrate' => 14,
                'fat' => 0,
                'sodium' => 1,
                'sugar' => 10,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Banán',
                'ingredientType' => 'Gyümölcs',
                'energy' => 89,
                'protein' => 1,
                'carbohydrate' => 23,
                'fat' => 0,
                'sodium' => 1,
                'sugar' => 12,
                'fiber' => 3,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Narancs',
                'ingredientType' => 'Gyümölcs',
                'energy' => 47,
                'protein' => 1,
                'carbohydrate' => 12,
                'fat' => 0,
                'sodium' => 0,
                'sugar' => 9,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Szőlő',
                'ingredientType' => 'Gyümölcs',
                'energy' => 69,
                'protein' => 1,
                'carbohydrate' => 18,
                'fat' => 0,
                'sodium' => 2,
                'sugar' => 16,
                'fiber' => 1,
                'isAvailable' => true
            ],
            
            // ============ ÁLTALÁNOS ALAPANYAGOK ============
            [
                'ingredientName' => 'Só',
                'ingredientType' => 'Fűszer',
                'energy' => 0,
                'protein' => 0,
                'carbohydrate' => 0,
                'fat' => 0,
                'sodium' => 38758,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Bors',
                'ingredientType' => 'Fűszer',
                'energy' => 251,
                'protein' => 10,
                'carbohydrate' => 64,
                'fat' => 3,
                'sodium' => 20,
                'sugar' => 1,
                'fiber' => 26,
                'isAvailable' => true
            ],

            [
                'ingredientName' => 'Liszt',
                'ingredientType' => 'Egyéb',
                'energy' => 364,
                'protein' => 10,
                'carbohydrate' => 76,
                'fat' => 1,
                'sodium' => 2,
                'sugar' => 0,
                'fiber' => 3,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Vaj',
                'ingredientType' => 'Tejtermék',
                'energy' => 717,
                'protein' => 1,
                'carbohydrate' => 0,
                'fat' => 81,
                'sodium' => 11,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Élesztő',
                'ingredientType' => 'Egyéb',
                'energy' => 105,
                'protein' => 8,
                'carbohydrate' => 18,
                'fat' => 2,
                'sodium' => 30,
                'sugar' => 0,
                'fiber' => 8,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Cukor',
                'ingredientType' => 'Egyéb',
                'energy' => 387,
                'protein' => 0,
                'carbohydrate' => 100,
                'fat' => 0,
                'sodium' => 1,
                'sugar' => 100,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Burgonya',
                'ingredientType' => 'Zöldség',
                'energy' => 77,
                'protein' => 2,
                'carbohydrate' => 17,
                'fat' => 0,
                'sodium' => 6,
                'sugar' => 1,
                'fiber' => 2,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Rizs',
                'ingredientType' => 'Egyéb',
                'energy' => 130,
                'protein' => 3,
                'carbohydrate' => 28,
                'fat' => 0,
                'sodium' => 1,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true
            ],
            [
                'ingredientName' => 'Búzaliszt',
                'ingredientType' => 'Egyéb',
                'energy' => 364,
                'protein' => 10,
                'carbohydrate' => 76,
                'fat' => 1,
                'sodium' => 2,
                'sugar' => 0,
                'fiber' => 3,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Tojás',
                'ingredientType' => 'Egyéb',
                'energy' => 155,
                'protein' => 13,
                'carbohydrate' => 1,
                'fat' => 11,
                'sodium' => 124,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true,
            ],
            
            [
                'ingredientName' => 'Paradicsom',
                'ingredientType' => 'Zöldség',
                'energy' => 18,
                'protein' => 1,
                'carbohydrate' => 4,
                'fat' => 0,
                'sodium' => 5,
                'sugar' => 3,
                'fiber' => 1,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Uborka',
                'ingredientType' => 'Zöldség',
                'energy' => 15,
                'protein' => 1,
                'carbohydrate' => 4,
                'fat' => 0,
                'sodium' => 2,
                'sugar' => 2,
                'fiber' => 1,
                'isAvailable' => true,
            ],
           
            [
                'ingredientName' => 'Hal',
                'ingredientType' => 'Hal',
                'energy' => 206,
                'protein' => 22,
                'carbohydrate' => 0,
                'fat' => 13,
                'sodium' => 61,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Rák',
                'ingredientType' => 'Hal',
                'energy' => 85,
                'protein' => 18,
                'carbohydrate' => 0,
                'fat' => 1,
                'sodium' => 119,
                'sugar' => 0,
                'fiber' => 0,
                'isAvailable' => true,
            ],
  
            [
                'ingredientName' => 'Mustár',
                'ingredientType' => 'Egyéb',
                'energy' => 66,
                'protein' => 4,
                'carbohydrate' => 6,
                'fat' => 4,
                'sodium' => 1135,
                'sugar' => 1,
                'fiber' => 3,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Mogyoró',
                'ingredientType' => 'Egyéb',
                'energy' => 628,
                'protein' => 15,
                'carbohydrate' => 17,
                'fat' => 61,
                'sodium' => 0,
                'sugar' => 4,
                'fiber' => 10,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Dió',
                'ingredientType' => 'Egyéb',
                'energy' => 654,
                'protein' => 15,
                'carbohydrate' => 14,
                'fat' => 65,
                'sodium' => 2,
                'sugar' => 2,
                'fiber' => 7,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Mandula',
                'ingredientType' => 'Egyéb',
                'energy' => 579,
                'protein' => 21,
                'carbohydrate' => 22,
                'fat' => 50,
                'sodium' => 1,
                'sugar' => 4,
                'fiber' => 13,
                'isAvailable' => true,
            ],
            [
                'ingredientName' => 'Földimogyoró',
                'ingredientType' => 'Egyéb',
                'energy' => 567,
                'protein' => 26,
                'carbohydrate' => 16,
                'fat' => 49,
                'sodium' => 18,
                'sugar' => 4,
                'fiber' => 9,
                'isAvailable' => true,
            ],
        ]);
    }
}